[build]
  command = "npm install && chmod +x node_modules/.bin/vite && npx vite build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]

[dev]
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  autoLaunch = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
